steps:
  - name: ':speech_balloon: Notify Maven repository deployment start'
    commands:
       - set -x
       - curl -v -X POST "${CHAT_WEBHOOK}&threadKey=${BUILDKITE_COMMIT}" -F "data={\"text\":\"This is a message\"}"
    plugins:
      - seek-oss/aws-sm#v2.0.0:
          env:
            NOTIFICATION_ENDPOINT:
              secret-id: stage-android-webviewsdk-buildkite
              json-key: .NOTIFICATION_ENDPOINT
            CHAT_WEBHOOK:
              secret-id: stage-android-webviewsdk-buildkite
              json-key: .CHAT_WEBHOOK
    agents:
      queue: stage-us-west-2-default
