steps:
  - name: ':hammer: Build Android RoktWebView SDK'
    commands:
      - bundle install
      - bundle exec fastlane buildAndroidSdkForPR
    artifact_paths:
      - "app/**/*.apk"
      - "roktwebviewsdk/**/*.aar"
    plugins:
      - docker-compose#v3.0.0:
          config: ./docker-compose.yml
          run: build_android
      - seek-oss/aws-sm#v2.0.0:
          env:
            STORE_PASSWORD:
              secret-id: 'stage-android-webviewsdk-buildkite'
              json-key: '.STORE_PASSWORD'
            KEY_ALIAS:
              secret-id: 'stage-android-webviewsdk-buildkite'
              json-key: '.KEY_ALIAS'
            KEY_PASSWORD:
              secret-id: 'stage-android-webviewsdk-buildkite'
              json-key: '.KEY_PASSWORD'
    agents:
      queue: 'stage-us-west-2-default'
    timeout_in_minutes: 25

  - name: ':hammer: Test Android RoktWebView SDK'
    key: "unit-tests"
    commands:
      - bundle install
      - bundle exec fastlane test
    artifact_paths:
      - "roktwebviewsdk/build/test-results/**/*.xml"
    plugins:
      - docker-compose#v3.0.0:
          config: ./docker-compose.yml
          run: build_android
    agents:
      queue: 'eng-default'
    timeout_in_minutes: 25

  - name: ':hammer: Build and UI Test'
    depends_on: 'unit-tests'
    commands:
      - bundle install
      - bundle exec fastlane deviceFarmUITest
    artifact_paths:
      - "app/**/*.apk"
      - "roktsdk/**/*.aar"
    plugins:
      - docker-compose#v3.0.0:
          config: ./docker-compose.yml
          run: build_android
      - seek-oss/aws-sm#v2.0.0:
          env:
            STORE_PASSWORD:
              secret-id: 'stage-android-webviewsdk-buildkite'
              json-key: '.STORE_PASSWORD'
            KEY_ALIAS:
              secret-id: 'stage-android-webviewsdk-buildkite'
              json-key: '.KEY_ALIAS'
            KEY_PASSWORD:
              secret-id: 'stage-android-webviewsdk-buildkite'
              json-key: '.KEY_PASSWORD'
            DEVICE_FARM_STAGE_ACCESS_KEY:
              secret-id: 'stage-android-webviewsdk-buildkite'
              json-key: '.DEVICE_FARM_STAGE_ACCESS_KEY'
            DEVICE_FARM_STAGE_DEVICE_POOL:
              secret-id: 'stage-android-webviewsdk-buildkite'
              json-key: '.DEVICE_FARM_STAGE_DEVICE_POOL'
            DEVICE_FARM_STAGE_PROJECT_NAME:
              secret-id: 'stage-android-webviewsdk-buildkite'
              json-key: '.DEVICE_FARM_STAGE_PROJECT_NAME'
            DEVICE_FARM_STAGE_SECRET_KEY:
              secret-id: 'stage-android-webviewsdk-buildkite'
              json-key: '.DEVICE_FARM_STAGE_SECRET_KEY'
    agents:
      queue: 'stage-us-west-2-default'
    timeout_in_minutes: 60

  - block: ":whale: Release to Maven"
    prompt: "Confirm releasing this version to Maven?"

  - name: ':rocket: Publish RoktWebView SDK to maven'
    commands:
      - bundle install
      - bundle exec fastlane publishToBintray
    artifact_paths:
      - "app/**/*.apk"
      - "roktwebviewsdk/**/*.aar"
    plugins:
      - docker-compose#v3.0.0:
          config: ./docker-compose.yml
          run: build_android
      - seek-oss/aws-sm#v2.0.0:
          env:
            STORE_PASSWORD:
              secret-id: 'stage-android-webviewsdk-buildkite'
              json-key: '.STORE_PASSWORD'
            KEY_ALIAS:
              secret-id: 'stage-android-webviewsdk-buildkite'
              json-key: '.KEY_ALIAS'
            KEY_PASSWORD:
              secret-id: 'stage-android-webviewsdk-buildkite'
              json-key: '.KEY_PASSWORD'
            BINTRAY_USER:
              secret-id: 'stage-android-webviewsdk-buildkite'
              json-key: '.BINTRAY_USER'
            BINTRAY_KEY:
              secret-id: 'stage-android-webviewsdk-buildkite'
              json-key: '.BINTRAY_KEY'
    agents:
      queue: 'stage-us-west-2-default'
    timeout_in_minutes: 25