steps:
  - name: ':speech_balloon: Notify Maven repository deployment start'
    commands:
      - "echo 1 ${CHAT_WEBHOOK}"
      - "echo 2 $${CHAT_WEBHOOK}"
      - "echo 3 $$CHAT_WEBHOOK"
      - "echo 4 $CHAT_WEBHOOK"

      - "curl -v -X POST -H \"Content-Type: application/json\" --data \"{\"text\": \"This is a message\"}\" $CHAT_WEBHOOK&threadKey=${BUILDKITE_COMMIT}"
    plugins:
      - seek-oss/aws-sm#v2.0.0:
          env:
            NOTIFICATION_ENDPOINT:
              secret-id: stage-android-webviewsdk-buildkite
              json-key: .NOTIFICATION_ENDPOINT
            CHAT_WEBHOOK:
              secret-id: stage-android-webviewsdk-buildkite
              json-key: .CHAT_WEBHOOK
    agents:
      queue: stage-us-west-2-default
